/**
 * NEAR AI Cloud HTTP client.
 *
 * Wraps the OpenAI-compatible gateway at `cloud-api.near.ai`. Everything is
 * thin — we add the Bearer header, surface upstream errors faithfully, and
 * return parsed JSON. Domain shaping happens in routes/lib higher up.
 */

import { request } from "undici";
import { config, hasNearKey } from "@/config.js";
import type { ChatRequestBody } from "@/types/index.js";

export class NearError extends Error {
  constructor(
    message: string,
    public status: number,
    public detail?: string
  ) {
    super(message);
    this.name = "NearError";
  }
}

interface RawChoice {
  index?: number;
  finish_reason?: string;
  message?: { role?: string; content?: string };
}

export interface RawChatCompletion {
  id?: string;
  object?: string;
  created?: number;
  model?: string;
  choices?: RawChoice[];
  usage?: {
    prompt_tokens?: number;
    completion_tokens?: number;
    total_tokens?: number;
  };
  attestation?: { tee?: string; hash?: string };
}

function authHeaders(): Record<string, string> {
  if (!hasNearKey) {
    throw new NearError("NEAR_API_KEY is not configured", 503);
  }
  return {
    "content-type": "application/json",
    authorization: `Bearer ${config.nearApiKey}`,
  };
}

async function parseJsonOrThrow(
  body: string,
  status: number
): Promise<Record<string, unknown>> {
  try {
    return JSON.parse(body) as Record<string, unknown>;
  } catch {
    throw new NearError("NEAR returned non-JSON response", 502, body.slice(0, 2000));
  }
}

/**
 * Non-streaming chat completion.
 * Streaming will land in a follow-up — see plan.md §11 (sandbox WS bridge).
 */
export async function chatCompletion(
  body: ChatRequestBody
): Promise<{ status: number; data: RawChatCompletion; latencyMs: number }> {
  const started = Date.now();
  const response = await request(`${config.nearApiBase}/v1/chat/completions`, {
    method: "POST",
    headers: authHeaders(),
    body: JSON.stringify({ ...body, stream: false }),
  });
  const text = await response.body.text();
  const latencyMs = Date.now() - started;

  if (response.statusCode >= 400) {
    throw new NearError(
      `NEAR upstream ${response.statusCode}`,
      response.statusCode,
      text.slice(0, 2000)
    );
  }

  const data = (await parseJsonOrThrow(text, response.statusCode)) as RawChatCompletion;
  return { status: response.statusCode, data, latencyMs };
}

/** GET /v1/models — proxy NEAR's OpenAI-compatible list endpoint. */
export async function listModels(): Promise<unknown> {
  const response = await request(`${config.nearApiBase}/v1/models`, {
    method: "GET",
    headers: authHeaders(),
  });
  const text = await response.body.text();
  if (response.statusCode >= 400) {
    throw new NearError(
      `NEAR upstream ${response.statusCode}`,
      response.statusCode,
      text.slice(0, 2000)
    );
  }
  return parseJsonOrThrow(text, response.statusCode);
}

/**
 * GET /v1/attestation/report — fetch a fresh attestation receipt from the gateway TEE.
 * Caller supplies a 64-char hex nonce; we fall back to one generated by NEAR if absent.
 */
export async function attestationReport(opts: {
  signingAlgo?: "ecdsa" | "ed25519";
  nonce?: string;
  includeTlsFingerprint?: boolean;
}): Promise<unknown> {
  const params = new URLSearchParams();
  params.set("signing_algo", opts.signingAlgo ?? "ecdsa");
  if (opts.nonce) params.set("nonce", opts.nonce);
  if (opts.includeTlsFingerprint) params.set("include_tls_fingerprint", "true");

  const response = await request(
    `${config.nearApiBase}/v1/attestation/report?${params.toString()}`,
    {
      method: "GET",
      headers: { accept: "application/json" },
    }
  );
  const text = await response.body.text();
  if (response.statusCode >= 400) {
    throw new NearError(
      `NEAR attestation ${response.statusCode}`,
      response.statusCode,
      text.slice(0, 2000)
    );
  }
  return parseJsonOrThrow(text, response.statusCode);
}
