export type NearModel = {
  modelName: string;
  modelId: string;
  creator: string;
  category: "Chat" | "Image" | "Embedding" | "Audio" | "Privacy" | "Rerank";
  contextLabel: string;
  contextTokens: number;
  inputPerM: string;
  outputPerM: string;
};

export const NEAR_MODELS: NearModel[] = [
  {
    modelName: "Claude Haiku 4.5",
    modelId: "anthropic/claude-haiku-4-5",
    creator: "Anthropic",
    category: "Chat",
    contextLabel: "200K",
    contextTokens: 200_000,
    inputPerM: "$1.00",
    outputPerM: "$5.00",
  },
  {
    modelName: "Claude Opus 4.6",
    modelId: "anthropic/claude-opus-4-6",
    creator: "Anthropic",
    category: "Chat",
    contextLabel: "200K",
    contextTokens: 200_000,
    inputPerM: "$5.00",
    outputPerM: "$25.00",
  },
  {
    modelName: "Claude Opus 4.7",
    modelId: "anthropic/claude-opus-4-7",
    creator: "Anthropic",
    category: "Chat",
    contextLabel: "1M",
    contextTokens: 1_000_000,
    inputPerM: "$5.00",
    outputPerM: "$25.00",
  },
  {
    modelName: "Claude Sonnet 4.5",
    modelId: "anthropic/claude-sonnet-4-5",
    creator: "Anthropic",
    category: "Chat",
    contextLabel: "200K",
    contextTokens: 200_000,
    inputPerM: "$3.00",
    outputPerM: "$15.50",
  },
  {
    modelName: "Claude Sonnet 4.6",
    modelId: "anthropic/claude-sonnet-4-6",
    creator: "Anthropic",
    category: "Chat",
    contextLabel: "1M",
    contextTokens: 1_000_000,
    inputPerM: "$3.00",
    outputPerM: "$15.00",
  },
  {
    modelName: "DeepSeek V3.1",
    modelId: "deepseek-ai/DeepSeek-V3.1",
    creator: "DeepSeek",
    category: "Chat",
    contextLabel: "128K",
    contextTokens: 128_000,
    inputPerM: "$1.00",
    outputPerM: "$2.50",
  },
  {
    modelName: "FLUX.2-klein-4B",
    modelId: "black-forest-labs/FLUX.2-klein-4B",
    creator: "Black Forest Labs",
    category: "Image",
    contextLabel: "128K",
    contextTokens: 128_000,
    inputPerM: "$1.00",
    outputPerM: "$1.00",
  },
  {
    modelName: "Gemini 2.5 Flash",
    modelId: "google/gemini-2.5-flash",
    creator: "Google",
    category: "Chat",
    contextLabel: "1M",
    contextTokens: 1_000_000,
    inputPerM: "$0.30",
    outputPerM: "$2.50",
  },
  {
    modelName: "Gemini 2.5 Flash Lite",
    modelId: "google/gemini-2.5-flash-lite",
    creator: "Google",
    category: "Chat",
    contextLabel: "1M",
    contextTokens: 1_049_000,
    inputPerM: "$0.10",
    outputPerM: "$0.40",
  },
  {
    modelName: "Gemini 2.5 Pro",
    modelId: "google/gemini-2.5-pro",
    creator: "Google",
    category: "Chat",
    contextLabel: "1M",
    contextTokens: 1_000_000,
    inputPerM: "$1.25",
    outputPerM: "$10.00",
  },
  {
    modelName: "Gemini 3.1 Flash Lite",
    modelId: "google/gemini-3.1-flash-lite",
    creator: "Google",
    category: "Chat",
    contextLabel: "1M",
    contextTokens: 1_049_000,
    inputPerM: "$0.25",
    outputPerM: "$1.50",
  },
  {
    modelName: "Gemini 3.5 Flash",
    modelId: "google/gemini-3.5-flash",
    creator: "Google",
    category: "Chat",
    contextLabel: "1M",
    contextTokens: 1_000_000,
    inputPerM: "$1.50",
    outputPerM: "$9.00",
  },
  {
    modelName: "Gemini 3 Pro Preview",
    modelId: "google/gemini-3-pro",
    creator: "Google",
    category: "Chat",
    contextLabel: "1M",
    contextTokens: 1_000_000,
    inputPerM: "$1.25",
    outputPerM: "$15.00",
  },
  {
    modelName: "Gemma 4 31B Instruct",
    modelId: "google/gemma-4-31B-it",
    creator: "Google",
    category: "Chat",
    contextLabel: "262K",
    contextTokens: 262_000,
    inputPerM: "$0.13",
    outputPerM: "$0.40",
  },
  {
    modelName: "Kimi K2.6",
    modelId: "moonshotai/kimi-k2.6",
    creator: "Moonshot",
    category: "Chat",
    contextLabel: "262K",
    contextTokens: 262_000,
    inputPerM: "$0.80",
    outputPerM: "$3.50",
  },
  {
    modelName: "GPT-4.1",
    modelId: "openai/gpt-4.1",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "1M",
    contextTokens: 1_000_000,
    inputPerM: "$2.00",
    outputPerM: "$8.00",
  },
  {
    modelName: "GPT-4.1 Mini",
    modelId: "openai/gpt-4.1-mini",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "1M",
    contextTokens: 1_000_000,
    inputPerM: "$0.40",
    outputPerM: "$1.60",
  },
  {
    modelName: "GPT-4.1 Nano",
    modelId: "openai/gpt-4.1-nano",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "1M",
    contextTokens: 1_000_000,
    inputPerM: "$0.10",
    outputPerM: "$0.40",
  },
  {
    modelName: "GPT-5",
    modelId: "openai/gpt-5",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "400K",
    contextTokens: 400_000,
    inputPerM: "$1.25",
    outputPerM: "$10.00",
  },
  {
    modelName: "GPT-5 Mini",
    modelId: "openai/gpt-5-mini",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "400K",
    contextTokens: 400_000,
    inputPerM: "$0.25",
    outputPerM: "$2.00",
  },
  {
    modelName: "GPT-5 Nano",
    modelId: "openai/gpt-5-nano",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "400K",
    contextTokens: 400_000,
    inputPerM: "$0.05",
    outputPerM: "$0.40",
  },
  {
    modelName: "GPT-5.1",
    modelId: "openai/gpt-5.1",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "400K",
    contextTokens: 400_000,
    inputPerM: "$1.25",
    outputPerM: "$10.00",
  },
  {
    modelName: "GPT-5.4",
    modelId: "openai/gpt-5.4",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "1.1M",
    contextTokens: 1_050_000,
    inputPerM: "$2.50",
    outputPerM: "$15.00",
  },
  {
    modelName: "GPT-5.4 Mini",
    modelId: "openai/gpt-5.4-mini",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "400K",
    contextTokens: 400_000,
    inputPerM: "$0.75",
    outputPerM: "$4.50",
  },
  {
    modelName: "GPT OSS 120B",
    modelId: "openai/gpt-oss-120b",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "131K",
    contextTokens: 131_000,
    inputPerM: "$0.15",
    outputPerM: "$0.55",
  },
  {
    modelName: "o3",
    modelId: "openai/o3",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "200K",
    contextTokens: 200_000,
    inputPerM: "$2.00",
    outputPerM: "$8.00",
  },
  {
    modelName: "o3 Mini",
    modelId: "openai/o3-mini",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "200K",
    contextTokens: 200_000,
    inputPerM: "$1.10",
    outputPerM: "$4.40",
  },
  {
    modelName: "o4 Mini",
    modelId: "openai/o4-mini",
    creator: "OpenAI",
    category: "Chat",
    contextLabel: "200K",
    contextTokens: 200_000,
    inputPerM: "$1.10",
    outputPerM: "$4.40",
  },
  {
    modelName: "Privacy Filter",
    modelId: "openai/privacy-filter",
    creator: "OpenAI",
    category: "Privacy",
    contextLabel: "512",
    contextTokens: 512,
    inputPerM: "$0.01",
    outputPerM: "—",
  },
  {
    modelName: "Whisper Large v3",
    modelId: "openai/whisper-large-v3",
    creator: "OpenAI",
    category: "Audio",
    contextLabel: "448",
    contextTokens: 448,
    inputPerM: "$0.01",
    outputPerM: "$0.01",
  },
  {
    modelName: "Qwen3 30B A3B Instruct 2507",
    modelId: "Qwen/Qwen3-30B-A3B-Instruct-2507",
    creator: "Alibaba",
    category: "Chat",
    contextLabel: "262K",
    contextTokens: 262_000,
    inputPerM: "$0.15",
    outputPerM: "$0.55",
  },
  {
    modelName: "Qwen3.5 122B A10B",
    modelId: "Qwen/Qwen3.5-122B-A10B",
    creator: "Alibaba",
    category: "Chat",
    contextLabel: "131K",
    contextTokens: 131_000,
    inputPerM: "$0.40",
    outputPerM: "$3.20",
  },
  {
    modelName: "Qwen 3.6 35B A3B FP8",
    modelId: "Qwen/Qwen3.6-35B-A3B-FP8",
    creator: "Alibaba",
    category: "Chat",
    contextLabel: "262K",
    contextTokens: 262_000,
    inputPerM: "$0.17",
    outputPerM: "$1.10",
  },
  {
    modelName: "Qwen3.7 Max",
    modelId: "qwen/qwen3.7-max",
    creator: "Alibaba",
    category: "Chat",
    contextLabel: "1M",
    contextTokens: 1_000_000,
    inputPerM: "$2.80",
    outputPerM: "$7.50",
  },
  {
    modelName: "Qwen3-Embedding-0.6B",
    modelId: "Qwen/Qwen3-Embedding-0.6B",
    creator: "Alibaba",
    category: "Embedding",
    contextLabel: "41K",
    contextTokens: 41_000,
    inputPerM: "$0.01",
    outputPerM: "$0.01",
  },
  {
    modelName: "Qwen3-Reranker-0.6B",
    modelId: "Qwen/Qwen3-Reranker-0.6B",
    creator: "Alibaba",
    category: "Rerank",
    contextLabel: "41K",
    contextTokens: 41_000,
    inputPerM: "$0.01",
    outputPerM: "$0.01",
  },
  {
    modelName: "Qwen3-VL-30B-A3B-Instruct",
    modelId: "Qwen/Qwen3-VL-30B-A3B-Instruct",
    creator: "Alibaba",
    category: "Chat",
    contextLabel: "256K",
    contextTokens: 256_000,
    inputPerM: "$0.15",
    outputPerM: "$0.55",
  },
  {
    modelName: "GLM 5.1",
    modelId: "zai-org/GLM-5.1-FP8",
    creator: "Z.ai",
    category: "Chat",
    contextLabel: "203K",
    contextTokens: 203_000,
    inputPerM: "$0.85",
    outputPerM: "$3.30",
  },
];

export const NEAR_CREATORS = Array.from(
  new Set(NEAR_MODELS.map((m) => m.creator))
).sort();

export const NEAR_CATEGORIES = ["Chat", "Image", "Embedding", "Audio"] as const;
